---
title: "Staging for local datasets"
author: "K Todd-Brown (ktoddbrown@gmail.com)"
date: "3/12/2018"
output: html_document
---
These datasets do not have a download option on them yet either because they are not published or are otherwise locally processed.

```{r setup}
library(tidyverse)
library(assertthat)
library(SoilDataR) #library(devtools); install_github("ISCN/soilDataR")

#mapping librarys to help with global/regional plots
library(ggmap)
library(maps)
library(mapdata)
library(fiftystater)

#install.packages("EML", repos = c("http://packages.ropensci.org", "https://cran.rstudio.com"))
library(EML)
```

# NEON
NEON contact provided a number of packaged zip files for example scripting.
```{r readData}
dataDir <- '~/Documents/Datasets/NEON_biogeochem/NEON_chem-soil-megapit/'

##big file here, not sure it's completely useful yet
#metaData <- read_eml(file.path(dataDir, "NEON.D01.BART.DP1.00097.001.2013-08.basic.20170707T141837Z", "NEON.D01.BART.DP1.00097.001.20130819-20130819.xml"))
csvFiles <- list.files(dataDir, pattern='*csv$', full.names=TRUE, recursive=TRUE)
#grepl('variables', csvFiles) #file with header key
# 
#dataLoad <- read_csv(csvFiles[grepl('variables', csvFiles)]) #given variable descriptors
#                                                             #...used to build key

NEONdata <- readKeyedData(filename=csvFiles[grepl('mgc_per', csvFiles)],
                          key.df=read_csv('../dataset_keys/NEON_devKey.csv'), verbose=TRUE)
```

```{r addUnits}
NEONdata$long <- NEONdata$key %>% 
  filter(!is.na(softType)) %>%
  filter(!is.na(hardUnit) | !is.na(hardMethod)) %>%
  rename(unit=hardUnit, method=hardMethod) %>%
  select(var, unit, method) %>%
  full_join(NEONdata$long)

#No hard coded values to merge for wide
```

```{r plotlocation}
mapWorld <- borders("world", colour="gray80", fill="gray80") # create a layer of borders
#ggplot() + mapWorld
ggplot(NEONdata$wide) +
  mapWorld + 
  #geom_hex(aes(x=long, y=lat), bins=200) + 
  geom_point(aes(x=lon, y=lat, color=observation_date)) +
  scale_fill_gradient(trans='log10') +
  theme_bw() +
  theme(text=element_text(size=18),
        legend.text=element_text(size=10),
        axis.title=element_blank())
```

```{r plotValues, fig.height=10}
print(unique(NEONdata$long$unit))

ggplot(NEONdata$long %>% filter(grepl('mol kg-1', unit))) +
  geom_histogram(aes(x=value)) +
  facet_wrap(~var+unit, scale='free')

ggplot(NEONdata$long %>% filter(grepl('g kg-1', unit))) +
  geom_histogram(aes(x=value)) +
  facet_wrap(~var+unit, scale='free')

ggplot(NEONdata$long %>% filter(grepl('l-1', unit))) +
  geom_histogram(aes(x=value)) +
  facet_wrap(~var+unit, scale='free')

ggplot(NEONdata$long %>% filter(!grepl('-1', unit))) +
  geom_histogram(aes(x=value)) +
  facet_wrap(~var+unit, scale='free')
```